version: "2"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  app:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    links:
      - mongo

